### ISSUE TITLE
No collision damage

### ISSUE THREAD

**Issue by Pyrolusite** [dsp2003/clef#6]
Unarmed melee monsters no longer inflict damage, neither by collision nor attacks like "Body Slam".
Ranged monsters only deal damage with their projectiles.

![Two monsters not inflicting damage](http://i.imgur.com/tahAdxC.png)

I'm using the current github build, along with Race Gameplay Variation and Ore Plants+ v1.17.
Starbound version : Glad Giraffe - Update 2 (Stable).

**Comment by dsp2003** [comment]
Hi! This was intended. Since a lot of people hated it (me is no exception) and because CF has added damage-on-touch to <b>every</b> monster in the game, I've decided to disable it entirely. There are two major points for me doing this:

* Even passive, non-hostile monsters do on-touch damage
* It has crippled the melee combat, made it unrealistic and frustrating. See this post from official CF's contributor, quiqksilver: https://www.reddit.com/r/starbound/comments/3wy99l/why_damage_on_touch_is_infuriating/

The problem with these monsters lies in their coding: the attacks are not really attacks, but actions they execute as player approaches them. When monster attacks you, you can actually see the attack name and icon on its health bar.

The properly coded attacks for these monsters is one of enhancements I'd like to include in this mod, but I'm still about to hear from my Lua scripter.

**Comment by Pyrolusite** [comment]
Oh, since I didn't find anything related to it on the mod description on Nexus, and seeing that even "proper attacks" were not doing anything I thought it was a bug.
Monsters with weapons are working fine though, so nevermind then :p

Thanks for the info and for maintaining the mod.
