### ISSUE TITLE
Lots of Colony microdungeons

### ISSUE THREAD

**Issue by AllanDoodes** [dsp2003/clef#7]
When I dig down into a planet I almost always find a huge shoal of microdungeons, primarily the colony one with a bed in and the one with lots of potted plants (sorry, I don't know their names). I also find the occassional much larger microdungoen, the one with three floors (including a basement with colony beds in and open ground ether side with two loghts each side). In their hndreds.

As far as I can tell, they occupy all the space in the seond and third zones, plus some of the first, and upwards of two-thirds of the width of the planet. And they are close together, so getting through them is messy.

This does only seem to happen when I use CLeF, and is a serious problem on almost all worlds (and I may merely have been lucky where I dug on the remaining worlds).

I do not know whether this is a intended feature or a bug, but it either needs documenting somewhere, or fixing.

I'm using the version current on GitHub as of 12/1/2016, Common and Sandbox.

Thank you.

**Comment by dsp2003** [comment]
Hello! :) These dungeons were injected into biome definitions, rather than planet type definitions, since they indeed have higher priority and spawn them more frequently. This was done for testing purposes (people were reporting random teleporting back to the ship), and I forgot to place them to terrestrial_worlds.config.patch instead. Sorry for inconvenience, I'll fix this soon. :)

The expanded three-floor one, however, should spawn as intended.

For the time being, you can remove their spawning by selectively deleting patches in CLeF - Common\biomes\surface (note some of these .patch files have extra lines beside the dungeon patching).

**Comment by dsp2003** [comment]
Done. Please re-download the latest version.
